version: '3'
services:
  todos_repository_mongodb:
    image: earthw0rm/todos_mongodb:1.0
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 1GB
      restart_policy:
        condition: on-failure
    build:
      context: ./mongo/
      dockerfile: Dockerfile
    expose:
      - "27017"
    networks:
      webnet:
        aliases:
        - todos_repository_mongodb

  todos_nodeapi:
    image: earthw0rm/todos_nodeapi:1.0
    build:
      context: ./backend/
      dockerfile: Dockerfile
    expose:
      - "8080"
    ports:
      - "8080:8080"
    privileged: true
    deploy:
      replicas: 4
      resources:
        limits:
          cpus: "0.5"
          memory: 512MB
      restart_policy:
        condition: on-failure      
    depends_on:
      - todos_repository_mongodb
    environment:
      - API_PORT=8080
      - CONNECTIONSTRING=mongodb://reactBack:senha123@todos_repository_mongodb:27017
    networks:
      webnet:
        aliases:
        - todos_nodeapi

  todos_web:
    image: earthw0rm/todos_web:1.0
    build:
      context: ./frontend/
      dockerfile: Dockerfile
      args:
        - API_URL=http://192.168.1.57:8080/api
    expose:
      - "80"
    ports:
      - "80:80"
    privileged: true
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.5"
          memory: 512MB
      restart_policy:
        condition: on-failure      

networks:
  webnet: